// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUuKoOHO23KhBS4pJfOBHrQFrZopHjIwU',
    appId: '1:434431094008:web:44d291050b57d905d89f0d',
    messagingSenderId: '434431094008',
    projectId: 'resto-91e62',
    authDomain: 'resto-91e62.firebaseapp.com',
    storageBucket: 'resto-91e62.firebasestorage.app',
    measurementId: 'G-0VKWDHL75Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxmUTqwD0bvdY1mF0gaq-18R-KaZXZWiQ',
    appId: '1:434431094008:android:df7bca99b95bc923d89f0d',
    messagingSenderId: '434431094008',
    projectId: 'resto-91e62',
    storageBucket: 'resto-91e62.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4GlU0gvQWmbOJDg-Hvv2jJ3cTG1r8DWY',
    appId: '1:434431094008:ios:431043698e2d745bd89f0d',
    messagingSenderId: '434431094008',
    projectId: 'resto-91e62',
    storageBucket: 'resto-91e62.firebasestorage.app',
    iosBundleId: 'com.example.myFirstProj',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4GlU0gvQWmbOJDg-Hvv2jJ3cTG1r8DWY',
    appId: '1:434431094008:ios:431043698e2d745bd89f0d',
    messagingSenderId: '434431094008',
    projectId: 'resto-91e62',
    storageBucket: 'resto-91e62.firebasestorage.app',
    iosBundleId: 'com.example.myFirstProj',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBUuKoOHO23KhBS4pJfOBHrQFrZopHjIwU',
    appId: '1:434431094008:web:3c9641d11f151888d89f0d',
    messagingSenderId: '434431094008',
    projectId: 'resto-91e62',
    authDomain: 'resto-91e62.firebaseapp.com',
    storageBucket: 'resto-91e62.firebasestorage.app',
    measurementId: 'G-68BNYGNQJ6',
  );
}
